---
- name: ensure docker is installed
  yum: name=docker state=present

- name: ensure pip is installed
  yum: name=python26-pip state=present

- name: ensure docker-py is installed
  pip: name=docker-py state=present version=0.6.0

- name: ensure docker service is running and enabled
  service: name=docker state=started enabled=yes
